package com.unchunks.echomark.data.remote

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class YouTubeCaptionsTest {

    private fun track(language: String, auto: Boolean = false) =
        CaptionTrack(baseUrl = "/api/timedtext?lang=$language&auto=$auto", languageCode = language, isAutoGenerated = auto)

    @Test
    fun player応答から字幕トラックを取り出し自動生成を見分ける() {
        val json = JSONObject(
            """
            {"captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[
              {"baseUrl":"https://www.youtube.com/api/timedtext?v=a&lang=ja","languageCode":"ja"},
              {"baseUrl":"https://www.youtube.com/api/timedtext?v=a&lang=en&kind=asr","languageCode":"en","kind":"asr"},
              {"languageCode":"fr"},
              {"baseUrl":"https://www.youtube.com/api/timedtext?v=a"}
            ]}}}
            """.trimIndent()
        )

        val tracks = YouTubeCaptions.parseTracks(json)

        assertEquals(
            listOf(
                CaptionTrack("https://www.youtube.com/api/timedtext?v=a&lang=ja", "ja", isAutoGenerated = false),
                CaptionTrack("https://www.youtube.com/api/timedtext?v=a&lang=en&kind=asr", "en", isAutoGenerated = true)
            ),
            tracks
        )
    }

    @Test
    fun 字幕が無い動画は空() {
        assertTrue(YouTubeCaptions.parseTracks(JSONObject("""{"playabilityStatus":{"status":"OK"}}""")).isEmpty())
        assertNull(YouTubeCaptions.selectTrack(emptyList()))
    }

    @Test
    fun 日本語は手動の字幕を自動生成より優先する() {
        val manual = track("ja")
        assertEquals(manual, YouTubeCaptions.selectTrack(listOf(track("en"), track("ja", auto = true), manual)))
    }

    @Test
    fun 日本語が無ければ話し言葉の字幕を英語より優先する() {
        // 自動生成の字幕の言語 = 動画で話されている言語
        val spoken = track("de-DE", auto = true)
        assertEquals(spoken, YouTubeCaptions.selectTrack(listOf(track("en"), spoken)))
        // 話し言葉の手動字幕があればそちらを使う
        val spokenManual = track("de")
        assertEquals(spokenManual, YouTubeCaptions.selectTrack(listOf(track("en"), spoken, spokenManual)))
    }

    @Test
    fun 地域つきの言語コードも同じ言語として扱う() {
        val japanese = track("ja-JP")
        assertEquals(japanese, YouTubeCaptions.selectTrack(listOf(track("en"), japanese)))
    }

    @Test
    fun 候補の言語も自動生成の字幕も無ければ先頭の手動字幕を使う() {
        val korean = track("ko")
        assertEquals(korean, YouTubeCaptions.selectTrack(listOf(korean, track("zh"))))
    }

    @Test
    fun 話し言葉の字幕が自動生成しか無ければそれを使う() {
        val spoken = track("fr", auto = true)
        assertEquals(spoken, YouTubeCaptions.selectTrack(listOf(track("ko"), spoken)))
    }

    @Test
    fun format3の字幕を1行1字幕の本文にする() {
        val xml = """
            <?xml version="1.0" encoding="utf-8" ?><timedtext format="3">
            <body>
            <p t="0" d="1000">[音楽]</p>
            <p t="1000" d="2000">こんにちは
            今日は Compose の話です</p>
            <p t="3000" d="2000" w="1"><s ac="0">hello</s><s t="200"> world</s></p>
            <p t="5000" d="10" a="1"></p>
            <p t="5010" d="2000"><s>hello</s><s> world</s></p>
            <p t="7000" d="2000">Tom &amp;amp; Jerry &amp;#39;s</p>
            </body></timedtext>
        """.trimIndent()

        assertEquals(
            "こんにちは 今日は Compose の話です\nhello world\nTom & Jerry 's",
            YouTubeCaptions.parseTimedText(xml)
        )
    }

    @Test
    fun 旧形式の字幕も読める() {
        val xml = """<?xml version="1.0"?><transcript><text start="0" dur="1">first &amp;#39;line&amp;#39;</text><text start="1" dur="1">[Music]</text><text start="2" dur="1">second</text></transcript>"""
        assertEquals("first 'line'\nsecond", YouTubeCaptions.parseTimedText(xml))
    }

    @Test
    fun 字幕本文は上限文字数で切り詰める() {
        val line = "あ".repeat(100)
        val xml = (0 until 400).joinToString("", "<timedtext><body>", "</body></timedtext>") { "<p>$line$it</p>" }
        val text = YouTubeCaptions.parseTimedText(xml)
        assertTrue(text.length <= YouTubeCaptions.MAX_TRANSCRIPT_CHARS)
        assertTrue(text.startsWith(line + "0\n" + line + "1"))
    }

    @Test
    fun 字幕が空のXMLは空文字() {
        assertEquals("", YouTubeCaptions.parseTimedText("""<timedtext format="3"><body></body></timedtext>"""))
        assertEquals("", YouTubeCaptions.parseTimedText(""))
    }
}
