package com.unchunks.echomark.data.remote

import org.json.JSONObject
import org.jsoup.Jsoup
import org.jsoup.parser.Parser

/**
 * YouTube の字幕トラック(player API の captionTracks の1件)。
 * @property isAutoGenerated 音声認識による自動生成の字幕(kind = "asr")か
 */
data class CaptionTrack(
    val baseUrl: String,
    val languageCode: String,
    val isAutoGenerated: Boolean
)

/** 取得した字幕の本文。 */
data class CaptionTranscript(
    val text: String,
    val languageCode: String,
    val isAutoGenerated: Boolean
)

/** YouTube の字幕の読み取り・選択・整形(純粋関数。JVM 単体テスト可能)。 */
internal object YouTubeCaptions {

    /** 字幕本文の上限文字数(クラウド API に渡す入力の上限に合わせる) */
    const val MAX_TRANSCRIPT_CHARS = 18_000

    /** player API の応答から字幕トラックの一覧を取り出す。字幕が無ければ空。 */
    fun parseTracks(playerResponse: JSONObject): List<CaptionTrack> {
        val tracks = playerResponse.optJSONObject("captions")
            ?.optJSONObject("playerCaptionsTracklistRenderer")
            ?.optJSONArray("captionTracks")
            ?: return emptyList()
        return (0 until tracks.length()).mapNotNull { index ->
            val track = tracks.optJSONObject(index) ?: return@mapNotNull null
            val baseUrl = track.optString("baseUrl").takeIf { it.isNotBlank() } ?: return@mapNotNull null
            val language = track.optString("languageCode").takeIf { it.isNotBlank() } ?: return@mapNotNull null
            CaptionTrack(baseUrl, language, isAutoGenerated = track.optString("kind") == "asr")
        }
    }

    /**
     * 要約に使う字幕を1つ選ぶ。言語は [preferredLanguages](日本語→英語)を優先し、次に動画の話し言葉
     * (自動生成の字幕の言語)、それも無ければ手動の字幕、最後に何でも。同じ言語なら手動の字幕を優先する。
     */
    fun selectTrack(tracks: List<CaptionTrack>, preferredLanguages: List<String> = listOf("ja", "en")): CaptionTrack? {
        if (tracks.isEmpty()) return null
        val spokenLanguage = tracks.firstOrNull { it.isAutoGenerated }?.let { baseLanguage(it.languageCode) }
        val languages = (preferredLanguages.take(1) + listOfNotNull(spokenLanguage) + preferredLanguages.drop(1)).distinct()
        for (language in languages) {
            val sameLanguage = tracks.filter { baseLanguage(it.languageCode) == language }
            (sameLanguage.firstOrNull { !it.isAutoGenerated } ?: sameLanguage.firstOrNull())?.let { return it }
        }
        return tracks.firstOrNull { !it.isAutoGenerated } ?: tracks.first()
    }

    /**
     * timedtext の XML(format 3 の `<p>`、旧形式の `<text>`)を、1行1字幕の本文にする。
     * 「[音楽]」のような効果音だけの行と、直前と同じ行(自動生成の字幕で起きる重複)は除く。
     */
    fun parseTimedText(xml: String): String {
        val document = Jsoup.parse(xml, "", Parser.xmlParser())
        val lines = mutableListOf<String>()
        var length = 0
        for (element in document.select("p, text")) {
            // 旧形式は実体参照が二重にエスケープされていることがある(&amp;#39; など)
            val line = Parser.unescapeEntities(element.text(), false)
                .replace(WHITESPACE, " ")
                .trim()
            if (line.isEmpty() || SOUND_ONLY.matches(line) || line == lines.lastOrNull()) continue
            lines += line
            length += line.length + 1
            if (length >= MAX_TRANSCRIPT_CHARS) break
        }
        return lines.joinToString("\n").take(MAX_TRANSCRIPT_CHARS)
    }

    /** "ja-JP" → "ja" のように、地域を除いた言語コードにする */
    private fun baseLanguage(code: String): String = code.substringBefore('-').lowercase()

    private val WHITESPACE = Regex("""\s+""")

    /** 角括弧だけの短い行(「[音楽]」「[拍手]」「[Music]」など) */
    private val SOUND_ONLY = Regex("""^[\[［(（][^\]］)）]{1,20}[\]］)）]$""")
}
