package com.unchunks.echomark.data.remote

import okhttp3.HttpUrl
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONObject
import timber.log.Timber
import java.io.ByteArrayOutputStream
import java.io.IOException
import java.io.InputStream

/**
 * YouTube 動画の字幕を取得する。
 *
 * ウォッチページに埋め込まれた字幕 URL は追加のトークン(PO トークン)が無いと空を返すため、
 * YouTube の Android アプリと同じクライアント情報で player API(InnerTube)を呼び、そこで返る字幕 URL を使う。
 * 公開 API ではないので、仕様が変わって取れなくなったときは null を返し、呼び出し側は説明文だけで要約を続ける。
 *
 * @param client 本文取得と同じ、ローカルアドレスへの接続を拒否するクライアント
 * @param playerEndpoint player API の URL(テストではローカルのサーバーに差し替える)
 */
internal class YouTubeTranscriptFetcher(
    private val client: OkHttpClient,
    private val playerEndpoint: HttpUrl = DEFAULT_PLAYER_ENDPOINT
) {

    /** [videoId] の字幕を取得する。字幕が無い・取得できないときは null(例外は投げない)。 */
    fun fetch(videoId: String): CaptionTranscript? = try {
        val track = YouTubeCaptions.selectTrack(YouTubeCaptions.parseTracks(player(videoId)))
        track?.let { download(it) }
    } catch (e: Exception) {
        Timber.w(e, "YouTube の字幕を取得できませんでした: %s", videoId)
        null
    }

    private fun player(videoId: String): JSONObject {
        require(VIDEO_ID.matches(videoId)) { "invalid video id" }
        val body = JSONObject()
            .put(
                "context",
                JSONObject().put(
                    "client",
                    JSONObject()
                        .put("clientName", CLIENT_NAME)
                        .put("clientVersion", CLIENT_VERSION)
                        .put("hl", "ja")
                )
            )
            .put("videoId", videoId)
            .toString()
        val request = Request.Builder()
            .url(playerEndpoint)
            .header("User-Agent", USER_AGENT)
            .post(body.toRequestBody(JSON))
            .build()
        return JSONObject(execute(request, MAX_PLAYER_BYTES))
    }

    private fun download(track: CaptionTrack): CaptionTranscript? {
        val url = trackUrl(track.baseUrl) ?: throw IOException("unexpected caption url")
        val request = Request.Builder().url(url).header("User-Agent", USER_AGENT).build()
        val text = YouTubeCaptions.parseTimedText(execute(request, MAX_CAPTION_BYTES))
        if (text.isBlank()) return null
        return CaptionTranscript(text, track.languageCode, track.isAutoGenerated)
    }

    /**
     * 字幕の URL。YouTube(https)か、player API と同じサーバーのものだけを許す。
     * 応答の内容をそのまま信用して任意の場所へ接続しないため。
     */
    private fun trackUrl(baseUrl: String): HttpUrl? {
        val url = playerEndpoint.resolve(baseUrl) ?: return null
        val isYouTube = url.isHttps && (url.host == "youtube.com" || url.host.endsWith(".youtube.com"))
        val isPlayerHost = url.scheme == playerEndpoint.scheme && url.host == playerEndpoint.host &&
            url.port == playerEndpoint.port
        return url.takeIf { isYouTube || isPlayerHost }
    }

    private fun execute(request: Request, maxBytes: Int): String =
        client.newCall(request).execute().use { response ->
            if (!response.isSuccessful) throw IOException("HTTP ${response.code}")
            val bytes = readCapped(response.body.byteStream(), maxBytes)
            String(bytes, response.body.contentType()?.charset() ?: Charsets.UTF_8)
        }

    /** 上限サイズまで読む。超えるものは途中で切れた XML・JSON になるので使わない */
    private fun readCapped(input: InputStream, maxBytes: Int): ByteArray {
        val out = ByteArrayOutputStream()
        val buffer = ByteArray(8 * 1024)
        while (true) {
            val read = input.read(buffer)
            if (read < 0) break
            if (out.size() + read > maxBytes) throw IOException("response too large")
            out.write(buffer, 0, read)
        }
        return out.toByteArray()
    }

    companion object {
        private val DEFAULT_PLAYER_ENDPOINT = "https://www.youtube.com/youtubei/v1/player".toHttpUrl()
        private const val CLIENT_NAME = "ANDROID"
        private const val CLIENT_VERSION = "20.10.38"
        private const val USER_AGENT =
            "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) EchoMark/1.0"
        private val JSON = "application/json".toMediaType()
        private val VIDEO_ID = Regex("""[A-Za-z0-9_-]{6,20}""")
        private const val MAX_PLAYER_BYTES = 4 * 1024 * 1024
        private const val MAX_CAPTION_BYTES = 2 * 1024 * 1024
    }
}
